from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):
    initial=True
    dependencies=[]
    operations=[
        migrations.CreateModel(name='AppConfig',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(default='default',max_length=80,unique=True)),('quote_asset',models.CharField(default='USDT',max_length=12)),('scan_interval',models.CharField(default='15m',max_length=8)),('scan_universe_size',models.PositiveIntegerField(default=30)),('signal_threshold',models.FloatField(default=72.0)),('paper_starting_cash',models.FloatField(default=10000.0)),('risk_per_trade_pct',models.FloatField(default=0.5)),('max_daily_loss_pct',models.FloatField(default=2.0)),('max_total_exposure_pct',models.FloatField(default=60.0)),('max_asset_exposure_pct',models.FloatField(default=15.0)),('max_open_positions',models.PositiveIntegerField(default=5)),('fee_bps',models.FloatField(default=10.0)),('slippage_bps',models.FloatField(default=5.0)),('stop_atr_multiple',models.FloatField(default=1.5)),('target_r_multiple',models.FloatField(default=2.2)),('updated_at',models.DateTimeField(auto_now=True))]),
        migrations.CreateModel(name='PaperAccount',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(default='primary',max_length=80,unique=True)),('starting_cash',models.FloatField(default=10000)),('cash',models.FloatField(default=10000)),('equity',models.FloatField(default=10000)),('peak_equity',models.FloatField(default=10000)),('max_drawdown_pct',models.FloatField(default=0)),('created_at',models.DateTimeField(default=django.utils.timezone.now)),('updated_at',models.DateTimeField(auto_now=True))]),
        migrations.CreateModel(name='MarketSignal',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('symbol',models.CharField(db_index=True,max_length=24)),('timeframe',models.CharField(default='15m',max_length=8)),('observed_at',models.DateTimeField(db_index=True,default=django.utils.timezone.now)),('price',models.FloatField()),('score',models.FloatField(db_index=True)),('trend_score',models.FloatField(default=0)),('momentum_score',models.FloatField(default=0)),('volume_score',models.FloatField(default=0)),('breakout_score',models.FloatField(default=0)),('volatility_score',models.FloatField(default=0)),('liquidity_score',models.FloatField(default=0)),('regime_score',models.FloatField(default=0)),('atr',models.FloatField(default=0)),('rsi',models.FloatField(default=0)),('volume_ratio',models.FloatField(default=0)),('spread_bps',models.FloatField(default=0)),('stop_price',models.FloatField(default=0)),('target_price',models.FloatField(default=0)),('rationale',models.TextField(blank=True)),('warnings',models.TextField(blank=True)),('is_actionable',models.BooleanField(default=False)),('data',models.JSONField(blank=True,default=dict))],options={'ordering':['-observed_at','-score']}),
        migrations.CreateModel(name='Trade',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('mode',models.CharField(choices=[('paper','Paper'),('testnet','Testnet'),('live','Live')],db_index=True,default='paper',max_length=10)),('symbol',models.CharField(db_index=True,max_length=24)),('status',models.CharField(choices=[('open','Open'),('closed','Closed'),('rejected','Rejected'),('error','Error')],db_index=True,default='open',max_length=12)),('opened_at',models.DateTimeField(db_index=True,default=django.utils.timezone.now)),('closed_at',models.DateTimeField(blank=True,null=True)),('entry_price',models.FloatField()),('quantity',models.FloatField()),('stop_price',models.FloatField()),('target_price',models.FloatField()),('exit_price',models.FloatField(blank=True,null=True)),('entry_fee',models.FloatField(default=0)),('exit_fee',models.FloatField(default=0)),('pnl',models.FloatField(default=0)),('pnl_pct',models.FloatField(default=0)),('exit_reason',models.CharField(blank=True,max_length=64)),('signal_score',models.FloatField(default=0)),('risk_amount',models.FloatField(default=0)),('order_id',models.CharField(blank=True,max_length=128)),('protection_order_id',models.CharField(blank=True,max_length=128)),('metadata',models.JSONField(blank=True,default=dict))],options={'ordering':['-opened_at']}),
        migrations.CreateModel(name='BacktestRun',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('symbol',models.CharField(max_length=24)),('timeframe',models.CharField(max_length=8)),('started_at',models.DateTimeField(default=django.utils.timezone.now)),('start_date',models.DateTimeField(blank=True,null=True)),('end_date',models.DateTimeField(blank=True,null=True)),('trades',models.PositiveIntegerField(default=0)),('win_rate_pct',models.FloatField(default=0)),('net_return_pct',models.FloatField(default=0)),('profit_factor',models.FloatField(default=0)),('max_drawdown_pct',models.FloatField(default=0)),('expectancy_pct',models.FloatField(default=0)),('sharpe',models.FloatField(default=0)),('results',models.JSONField(blank=True,default=dict))],options={'ordering':['-started_at']}),
        migrations.CreateModel(name='LiveGate',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('checked_at',models.DateTimeField(default=django.utils.timezone.now)),('eligible',models.BooleanField(default=False)),('paper_days',models.PositiveIntegerField(default=0)),('closed_trades',models.PositiveIntegerField(default=0)),('net_profit',models.FloatField(default=0)),('profit_factor',models.FloatField(default=0)),('expectancy',models.FloatField(default=0)),('max_drawdown_pct',models.FloatField(default=0)),('reasons',models.JSONField(default=list)),('requirements',models.JSONField(default=dict))],options={'ordering':['-checked_at']}),
        migrations.CreateModel(name='AuditEvent',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(db_index=True,default=django.utils.timezone.now)),('level',models.CharField(default='INFO',max_length=12)),('category',models.CharField(db_index=True,max_length=40)),('message',models.TextField()),('data',models.JSONField(blank=True,default=dict))],options={'ordering':['-created_at']}),
        migrations.AddIndex(model_name='marketsignal',index=models.Index(fields=['symbol','-observed_at'],name='trading_mar_symbol_11a2f7_idx')),
    ]
