STRATEGY_VERSION = "2.0"
STRATEGY_VERSION_SLUG = "v2"
BACKTEST_ENGINE_VERSION = "2.1"
RESEARCH_ENGINE_VERSION = "2.2"
RESEARCH_DEFAULT_DAYS = 1095
RESEARCH_SPLIT_DATE = "2026-01-01"
RESEARCH_INTERVALS = ("1h", "4h")
RESEARCH_WALK_FORWARD_DAYS = 90

REENTRY_COOLDOWN_MINUTES = 60
MAX_SIGNAL_AGE_MINUTES = 20
MIN_BREAKOUT_VOLUME_RATIO = 1.05
MAX_ACTIONABLE_SPREAD_BPS = 20.0
MIN_TREND_SCORE = 65.0
MIN_MOMENTUM_SCORE = 50.0
MAX_BREAKOUT_EXTENSION_PCT = 1.8
MAX_ENTRY_RSI = 72.0

CORE_BASES = {
    "BTC", "ETH", "BNB", "SOL", "XRP", "ADA", "DOGE", "LINK", "AVAX",
    "LTC", "TRX", "SUI", "TON", "NEAR", "DOT", "BCH", "UNI", "AAVE",
    "ETC", "ATOM", "HBAR", "ICP", "FIL", "APT", "ARB", "OP", "XLM",
    "INJ", "SEI", "RENDER",
}
