STRATEGY_VERSION = "2.0"
STRATEGY_VERSION_SLUG = "v2"
BACKTEST_ENGINE_VERSION = "2.1"
RESEARCH_ENGINE_VERSION = "2.2"
RESEARCH_DEFAULT_DAYS = 1095
RESEARCH_SPLIT_DATE = "2026-01-01"
RESEARCH_INTERVALS = ("1h", "4h")
RESEARCH_WALK_FORWARD_DAYS = 90

REENTRY_COOLDOWN_MINUTES = 60
MAX_SIGNAL_AGE_MINUTES = 20
MIN_BREAKOUT_VOLUME_RATIO = 1.05
MAX_ACTIONABLE_SPREAD_BPS = 20.0
MIN_TREND_SCORE = 65.0
MIN_MOMENTUM_SCORE = 50.0
MAX_BREAKOUT_EXTENSION_PCT = 1.8
MAX_ENTRY_RSI = 72.0

CORE_BASES = {
    "BTC", "ETH", "BNB", "SOL", "XRP", "ADA", "DOGE", "LINK", "AVAX",
    "LTC", "TRX", "SUI", "TON", "NEAR", "DOT", "BCH", "UNI", "AAVE",
    "ETC", "ATOM", "HBAR", "ICP", "FIL", "APT", "ARB", "OP", "XLM",
    "INJ", "SEI", "RENDER",
}

# Candidate Validation Lab v2.3
CANDIDATE_VALIDATION_ENGINE_VERSION = "2.3"
CANDIDATE_THRESHOLD_GRID = (72.0, 75.0, 78.0, 80.0, 82.0, 85.0)
# 80 is the forward-test hypothesis identified before running this threshold grid.
CANDIDATE_FORWARD_THRESHOLD = 80.0
CANDIDATE_VALIDATION_SET = (
    ("INJUSDT", "1h"),
    ("ATOMUSDT", "1h"),
    ("ATOMUSDT", "4h"),
    ("TRXUSDT", "4h"),
)

# Separate paper experiment: never counted in Strategy v2.0 live-gate statistics.
CANDIDATE_PAPER_VERSION = "2.3-candidate"
CANDIDATE_PAPER_ACCOUNT_NAME = "candidate-v23"
CANDIDATE_PAPER_THRESHOLD = 80.0
CANDIDATE_PAPER_SYMBOLS = ("INJUSDT", "ATOMUSDT")
CANDIDATE_PAPER_INTERVAL = "1h"
CANDIDATE_PAPER_MAX_HOLD_HOURS = 24
